name: Markdownlint

on:
  pull_request:
    paths:
    - ".github/workflows/markdownlint-problem-matcher.json"
    - ".github/workflows/markdownlint.yml"
    - ".markdownlint.json"
    - "package*.json"
    - "**/*.md"

  push:
    branches-ignore:
    - "dependabot/**"
    paths:
    - ".github/workflows/markdownlint-problem-matcher.json"
    - ".github/workflows/markdownlint.yml"
    - ".markdownlint.json"
    - "package*.json"
    - "**/*.md"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 23

      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Markdownlint
        run: |
          echo "::add-matcher::.github/workflows/markdownlint-problem-matcher.json"
          npm run lint
